name: football
description: "Football Stats Dashboard - A professional portfolio MVP."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management & Navigation
  get: ^4.6.6

  # Networking
  dio: ^5.7.0

  # UI Enhancements
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
